CREATE DATABASE IF NOT EXISTS ClinicaDental;

USE ClinicaDental;

CREATE TABLE PACIENTES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  dni VARCHAR(10) NOT NULL,
  fecha_ingreso DATE NOT NULL,
  domicilio_id INT NOT NULL,
  FOREIGN KEY (domicilio_id) REFERENCES DOMICILIO(id)
);

CREATE TABLE DOMICILIO (
  id INT AUTO_INCREMENT PRIMARY KEY,
  calle VARCHAR(50) NOT NULL,
  numero INT NOT NULL,
  localidad VARCHAR(50) NOT NULL,
  provincia VARCHAR(50) NOT NULL
);
