DROP TABLE  IF EXISTS DOMICILIOS

CREATE TABLE DOMICILIOS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  calle VARCHAR(100) ,
  numero INT,
  localidad VARCHAR(100) ,
  provincia VARCHAR(100) ,
);
**
CREATE TABLE PACIENTES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) ,
  apellido VARCHAR(50) ,
  dni VARCHAR(10) ,
  fechaIngreso DATE ,
  domicilio_id INT);